### ISSUE TITLE
README links to archived repository

### ISSUE THREAD

**Issue by jelly** [RedHatInsights/insights-inventory-frontend#1882]
The README links to a comprehensive documentation available here https://github.com/RedHatInsights/insights-frontend-storybook/blob/master/src/docs/welcome/quickStart/DOC.md

But that repository is archived so I assume this is no longer valid/relevant?

**Comment by leSamo** [comment]
Hey, this link contains information on how to setup the template, this repo is based upon; it should have been removed a couple of years ago, when the template was adapted. I will refresh the README content, thanks for pointing that out.
