### ISSUE TITLE
Inventory > System X details -- change tab order

### ISSUE THREAD

**Issue by KendraMar** [RedHatInsights/insights-inventory-frontend#77]
Can we change the tab order to:

Rules
Vulnerabilities
Compliance
General Information

![bitmoji](https://render.bitstrips.com/v2/cpanel/d27a2dfb-c3b9-44fd-8e5e-4e3068049585-72aa3dc5-4103-46f8-b4b4-24feb7f82415-v1.png?transparent=1&palette=1&width=246)

**Comment by ryelo** [comment]
@KendraMar Is "Rules" taking the place of "Insights"?

**Comment by KendraMar** [comment]
Yup, per Rob...
